language: rust
rust:
- stable
cache: cargo
before_deploy:
- cargo build --release --verbose
- mkdir release
- cp target/release/rust_chess release/rust_chess
deploy:
  provider: releases
  api_key:
    secure: iLK7CTS9y2r+zBzYT/uJjJpBFSnhiT1EejUBfcpK38j0vDALke1+8gODHT6lSGUaeyWBGzsho0ztt3je/lILriIJWMKkj2DsYdXOoAhJ+Tm5i+CnimACPCdWsOnCxrOPYwqlGPFduvQyUK5HWV1Ply/agmf7t0TJtIKB0sxrESW1neBPNZgOZftnsk1zI9EG+FgkJA3PIXWjqlorRBNlUuw/PGOCdTxFV5AQJ4hcVtGU04A69Sq3WADdO4Y6qe4HdbHxwi7wEca/K82HTsp7NuuC9mg5i2EvM5Yqr4wK1lAsvWMDAMEJjwLAdhhgeRX6Fbmr0EhwZ32wnvSiZyKJZ4wH2tXmmK0eShcoRc8Gci9hiHIw9trJV1Rm9tqeltdWs9FRz7ZaaxCANsqpoxorJYUsbTUM5f+hnfwi+gh1h2RL0b/lcWfcXu08AMUg8QDM+mtgt9Y3Anp7sHvEOGUOg9f+DIfsoLLuT2e3OCZB7txd4ZSIct/pOIjILCh4k5LyNsCpXVxzJz0hqyuosv/gTWnlzAMX4tjwPkUk1WzSCD75NAhqVtOEwE/3KtbiFe4XlEmAxTdtf8wE9mFyUAkNGAlLxphPPD8SroqLfZRAV35Vyn67UeKuylc+UM0KJUnwSa0Kds/wEZPONIFjJdRntk59zkImCxI2cxUZxY2KH/w=
  file: release/rust_chess
  on:
    repo: jheek/rust-chess
